// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Google OAuth web client ID used by `google_sign_in` on web.
  static const String webGoogleClientId =
      '895619974573-jk4j5vhlog4k6rjjmvogrtmdthm4s8ka.apps.googleusercontent.com';

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXwYYH34kX2UM5Y7X1W3ggja61mzlToX0',
    appId: '1:895619974573:web:66c319b9baf0d0223e8d24',
    messagingSenderId: '895619974573',
    projectId: 'taskmate-chat-test',
    authDomain: 'taskmate-chat-test.firebaseapp.com',
    storageBucket: 'taskmate-chat-test.firebasestorage.app',
    measurementId: 'G-JK49WB3DHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOc8gu0Ftz25AXwYjQgrdYkuzrWwRUIaE',
    appId: '1:895619974573:android:e75adb73f277b4043e8d24',
    messagingSenderId: '895619974573',
    projectId: 'taskmate-chat-test',
    storageBucket: 'taskmate-chat-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6TRqgt0qNqNwKWBKOPzoZrIunty2MaKo',
    appId: '1:895619974573:ios:7ba8f2ac7cee82ed3e8d24',
    messagingSenderId: '895619974573',
    projectId: 'taskmate-chat-test',
    storageBucket: 'taskmate-chat-test.firebasestorage.app',
    iosBundleId: 'com.saiman.taskmate.capstoneProject',
  );
}
